sonar.projectKey=Firefox2100_roleplay-catalogue-client
sonar.organization=firefox2100
sonar.projectName=Roleplay Catalogue Client
sonar.sources=src,src-tauri/src
sonar.tests=src,src-tauri/src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**,src-tauri/src/function_tests.rs,src-tauri/src/integration_tests.rs
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**,src-tauri/src/function_tests.rs,src-tauri/src/integration_tests.rs
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.rust.lcov.reportPaths=coverage/rust-lcov.info
sonar.testExecutionReportPaths=test-results-sonar.xml
sonar.rust.cargo.manifestPaths=src-tauri/Cargo.toml
sonar.sourceEncoding=UTF-8
