import { useEffect, useRef, useState } from "react";
import { clearResourceCover, fetchCharacterCover, fetchImageContent, listOwnedImages, selectResourceCover, uploadResourceCover } from "./backend";
import type { MessageKey } from "./i18n";
import type { CatalogueResource, CharacterAsset, CharacterCardV3Data, CoverImage, SelectedResource } from "./types";
import "./AssetsPage.css";

const imageUrl = (image: CoverImage | null) => image ? `data:${image.mediaType};base64,${image.data}` : "";
const blankAsset = (): CharacterAsset => ({ type: "icon", uri: "", name: "", ext: "png" });

export function AssetsPage({ selected, dirty, status, onCardChange, onResource, onSave, t }: { selected: SelectedResource; dirty: boolean; status: "idle" | "saving" | "saved" | "error"; onCardChange: ((card: CharacterCardV3Data) => void) | null; onResource: (resource: CatalogueResource) => void; onSave: () => void; t: (key: MessageKey) => string }) {
  const card = selected.resource.resourceType === "sillytavern/character" ? selected.draft?.data as CharacterCardV3Data | undefined : undefined;
  const assets = card?.assets ?? [];
  const [selectedAsset, setSelectedAsset] = useState(0);
  const [cover, setCover] = useState<CoverImage | null>(null);
  const [images, setImages] = useState<CatalogueResource[]>([]);
  const [thumbnails, setThumbnails] = useState<Record<string, CoverImage>>({});
  const [coverStatus, setCoverStatus] = useState<"loading" | "idle" | "saving" | "error">("loading");
  const [deleteAsset, setDeleteAsset] = useState(false);
  const [clearCoverOpen, setClearCoverOpen] = useState(false);
  const [assetError, setAssetError] = useState("");
  const fileInput = useRef<HTMLInputElement>(null);
  const assetInput = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; const local = selected.resource.storageMode === "local"; Promise.all([fetchCharacterCover(selected.resource.id), local ? Promise.resolve({ items: [], nextOffset: null }) : listOwnedImages()]).then(async ([current, list]) => { if (!active) return; setCover(current); setImages(list.items); const loaded = await Promise.all(list.items.map(async (image) => { try { return [image.id, await fetchImageContent(image.id)] as const; } catch { return null; } })); if (active) { setThumbnails(Object.fromEntries(loaded.filter((item): item is readonly [string, CoverImage] => Boolean(item)))); setCoverStatus("idle"); } }).catch(() => active && setCoverStatus("error")); return () => { active = false; }; }, [selected.resource.id, selected.resource.storageMode]);
  const updateAssets = (next: CharacterAsset[]) => { if (card && onCardChange) onCardChange({ ...card, assets: next }); };
  const patchAsset = <K extends keyof CharacterAsset>(key: K, value: CharacterAsset[K]) => updateAssets(assets.map((asset, index) => index === selectedAsset ? { ...asset, [key]: value } : asset));
  const chooseCover = async (image: CatalogueResource) => { setCoverStatus("saving"); try { const resource = await selectResourceCover(selected.resource.id, image.id); onResource(resource); setCover(thumbnails[image.id] ?? await fetchImageContent(image.id)); setCoverStatus("idle"); } catch { setCoverStatus("error"); } };
  const clearCover = async () => { setClearCoverOpen(false); setCoverStatus("saving"); try { const resource = await clearResourceCover(selected.resource.id); onResource(resource); setCover(null); setCoverStatus("idle"); } catch { setCoverStatus("error"); } };
  const uploadCover = async (file: File) => { setCoverStatus("saving"); try { const extension = file.name.split(".").pop()?.toLowerCase(); const inferred = extension === "png" ? "image/png" : extension === "webp" ? "image/webp" : extension === "gif" ? "image/gif" : extension === "avif" ? "image/avif" : "image/jpeg"; const bytes = Array.from(new Uint8Array(await file.arrayBuffer())); const resource = await uploadResourceCover(selected.resource.id, file.name, file.type || inferred, bytes); onResource(resource); const nextCover = await fetchCharacterCover(selected.resource.id); setCover(nextCover); if (selected.resource.storageMode !== "local") { const list = await listOwnedImages(); setImages(list.items); } if (resource.coverImageResourceId && nextCover) setThumbnails((currentThumbnails) => ({ ...currentThumbnails, [resource.coverImageResourceId!]: nextCover })); setCoverStatus("idle"); } catch { setCoverStatus("error"); } };
  const embedAsset = (file: File) => { if (file.size > 5 * 1024 * 1024) { setAssetError(t("assetTooLarge")); return; } const reader = new FileReader(); reader.onerror = () => setAssetError(t("assetReadError")); reader.onload = () => { if (typeof reader.result !== "string") return; const extension = file.name.includes(".") ? file.name.split(".").pop() ?? "" : ""; setAssetError(""); updateAssets(assets.map((asset, index) => index === selectedAsset ? { ...asset, uri: reader.result as string, name: asset.name || file.name.replace(/\.[^.]+$/, ""), ext: extension || asset.ext, type: file.type.startsWith("audio/") ? "audio" : asset.type } : asset)); }; reader.readAsDataURL(file); };
  const current = assets[selectedAsset] ?? null;
  return <section className="assets-page"><header><div><p>{selected.resource.metadata.name}</p><h1>{t("assetsAndCover")}</h1><span>{t("assetsAndCoverIntro")}</span></div><aside><strong>{t("assetBoundary")}</strong><p>{t("assetBoundaryHint")}</p></aside></header>
    <section className="cover-section"><div className="cover-preview">{cover ? <img src={imageUrl(cover)} alt={t("currentCover")} /> : <span aria-hidden="true">◇</span>}</div><div className="cover-copy"><h2>{t("catalogueCover")}</h2><p>{t("catalogueCoverHint")}</p><div><button className="primary" disabled={coverStatus === "saving"} onClick={() => fileInput.current?.click()}>{coverStatus === "saving" ? t("uploading") : t("uploadNewCover")}</button>{cover && <button className="danger-outline" disabled={coverStatus === "saving"} onClick={() => setClearCoverOpen(true)}>{t("clearCover")}</button>}<input ref={fileInput} hidden type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadCover(file); event.target.value = ""; }} />{coverStatus === "error" && <span role="alert">{t("coverUpdateError")}</span>}</div></div></section>
    {selected.resource.storageMode !== "local" && <section className="image-library"><header><div><h2>{t("ownedImages")}</h2><p>{t("ownedImagesHint")}</p></div><span>{images.length}</span></header>{images.length ? <div>{images.map((image) => <button className={selected.resource.coverImageResourceId === image.id ? "active" : ""} key={image.id} onClick={() => void chooseCover(image)}><span>{thumbnails[image.id] ? <img src={imageUrl(thumbnails[image.id])} alt="" /> : "◇"}</span><strong>{image.metadata.name}</strong><small>{selected.resource.coverImageResourceId === image.id ? t("currentCover") : t("useAsCover")}</small></button>)}</div> : <p className="asset-empty">{t("noOwnedImages")}</p>}</section>}
    {card && current && <div className="asset-embed"><button className="secondary" onClick={() => assetInput.current?.click()}>{t("embedAssetFile")}</button><input ref={assetInput} hidden type="file" accept="image/*,audio/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) embedAsset(file); event.target.value = ""; }} /><span>{t("embedAssetHint")}</span>{assetError && <strong role="alert">{assetError}</strong>}</div>}
    {card && <section className="v3-assets"><header><div><h2>{t("v3Assets")}</h2><p>{t("v3AssetsHint")}</p></div><button className="primary" onClick={() => { updateAssets([...assets, blankAsset()]); setSelectedAsset(assets.length); }}>{t("addAsset")}</button></header><div className="asset-workspace"><aside>{assets.map((asset, index) => <button className={selectedAsset === index ? "active" : ""} key={`${asset.name}-${index}`} onClick={() => setSelectedAsset(index)}><strong>{asset.name || `${t("asset")} ${index + 1}`}</strong><small>{asset.type} · {asset.ext}</small></button>)}</aside><div className="asset-editor">{current ? <><div className="asset-fields"><label>{t("assetName")}<input value={current.name} onChange={(event) => patchAsset("name", event.target.value)} /></label><label>{t("assetType")}<select value={current.type} onChange={(event) => patchAsset("type", event.target.value)}><option value="icon">icon</option><option value="emotion">emotion</option><option value="background">background</option><option value="audio">audio</option><option value="other">other</option></select></label><label>{t("assetExtension")}<input value={current.ext} onChange={(event) => patchAsset("ext", event.target.value.replace(/^\./, ""))} /></label><label className="wide">{t("assetUri")}<input value={current.uri} onChange={(event) => patchAsset("uri", event.target.value)} /><small>{t("assetUriHint")}</small></label></div>{current.uri.startsWith("data:image/") && <img className="asset-data-preview" src={current.uri} alt={current.name} />}<footer><button className="secondary" disabled={selectedAsset === 0} onClick={() => { const next = [...assets]; [next[selectedAsset - 1], next[selectedAsset]] = [next[selectedAsset], next[selectedAsset - 1]]; updateAssets(next); setSelectedAsset(selectedAsset - 1); }}>{t("moveUp")}</button><button className="secondary" disabled={selectedAsset === assets.length - 1} onClick={() => { const next = [...assets]; [next[selectedAsset + 1], next[selectedAsset]] = [next[selectedAsset], next[selectedAsset + 1]]; updateAssets(next); setSelectedAsset(selectedAsset + 1); }}>{t("moveDown")}</button><button className="danger-outline" onClick={() => setDeleteAsset(true)}>{t("remove")}</button></footer></> : <p className="asset-empty">{t("noV3Assets")}</p>}</div></div></section>}
    {card && <div className="extensions-save-bar"><span>{status === "saved" ? t("assetsSaved") : status === "error" ? t("assetsSaveError") : dirty ? t("unsavedChanges") : ""}</span><button className="primary" disabled={!dirty || status === "saving"} onClick={onSave}>{status === "saving" ? t("saving") : t("saveAssets")}</button></div>}
    {deleteAsset && <div className="confirmation-layer"><section className="confirmation-dialog" role="alertdialog" aria-modal="true"><h2>{t("removeAssetTitle")}</h2><p>{t("removeAssetBody")}</p><div><button className="secondary" autoFocus onClick={() => setDeleteAsset(false)}>{t("cancel")}</button><button className="danger-button" onClick={() => { updateAssets(assets.filter((_, index) => index !== selectedAsset)); setSelectedAsset(Math.max(0, selectedAsset - 1)); setDeleteAsset(false); }}>{t("remove")}</button></div></section></div>}
    {clearCoverOpen && <div className="confirmation-layer"><section className="confirmation-dialog" role="alertdialog" aria-modal="true"><h2>{t("clearCoverTitle")}</h2><p>{t("clearCoverBody")}</p><div><button className="secondary" autoFocus onClick={() => setClearCoverOpen(false)}>{t("cancel")}</button><button className="danger-button" onClick={() => void clearCover()}>{t("clearCover")}</button></div></section></div>}
  </section>;
}
