import { invoke } from "@tauri-apps/api/core";
import type { AiConversation, AppConfig, BootstrapData, CharacterCardV3Data, CharacterDraft, CoverImage, CreateResourceInput, LorebookData, LorebookDraft, ResourceList, SelectedResource, SendAiMessageInput, WorldOverview } from "./types";
export const loadBootstrap = () => invoke<BootstrapData>("load_bootstrap");
export const saveConfiguration = (config: AppConfig) => invoke<AppConfig>("save_configuration", { config });
export const listOwnedResources = (resourceType: CreateResourceInput["resourceType"]) => invoke<ResourceList>("list_owned_resources", { resourceType });
export const fetchCharacterCover = (resourceId: string) => invoke<CoverImage | null>("fetch_character_cover", { resourceId });
export const selectResource = (resourceId: string, resourceType: CreateResourceInput["resourceType"]) => invoke<SelectedResource>("select_resource", { resourceId, resourceType });
export const createResource = (input: CreateResourceInput) => invoke<SelectedResource>("create_resource", { input });
export const saveCharacterDraft = (resourceId: string, data: CharacterCardV3Data) => invoke<CharacterDraft>("save_character_draft", { resourceId, data });
export const saveLorebookDraft = (resourceId: string, data: LorebookData) => invoke<LorebookDraft>("save_lorebook_draft", { resourceId, data });
export const listAiConversations = (resourceId: string | null) => invoke<AiConversation[]>("list_ai_conversations", { resourceId });
export const deleteAiConversation = (conversationId: string) => invoke<void>("delete_ai_conversation", { conversationId });
export const sendAiMessage = (input: SendAiMessageInput) => invoke<AiConversation>("send_ai_message", { input });
export const loadWorldOverview = (resourceId: string) => invoke<WorldOverview>("load_world_overview", { resourceId });
export const saveWorldOverview = (overview: WorldOverview) => invoke<WorldOverview>("save_world_overview", { overview });
