import { invoke } from "@tauri-apps/api/core";
import type { AiConversation, AppConfig, BootstrapData, CoverImage, CreateCharacterInput, ResourceList, SelectedCharacter, SendAiMessageInput, WorldOverview } from "./types";
export const loadBootstrap = () => invoke<BootstrapData>("load_bootstrap");
export const saveConfiguration = (config: AppConfig) => invoke<AppConfig>("save_configuration", { config });
export const listOwnedCharacters = () => invoke<ResourceList>("list_owned_characters");
export const fetchCharacterCover = (resourceId: string) => invoke<CoverImage | null>("fetch_character_cover", { resourceId });
export const selectCharacter = (resourceId: string) => invoke<SelectedCharacter>("select_character", { resourceId });
export const createCharacter = (input: CreateCharacterInput) => invoke<SelectedCharacter>("create_character", { input });
export const listAiConversations = (resourceId: string | null) => invoke<AiConversation[]>("list_ai_conversations", { resourceId });
export const deleteAiConversation = (conversationId: string) => invoke<void>("delete_ai_conversation", { conversationId });
export const sendAiMessage = (input: SendAiMessageInput) => invoke<AiConversation>("send_ai_message", { input });
export const loadWorldOverview = (resourceId: string) => invoke<WorldOverview>("load_world_overview", { resourceId });
export const saveWorldOverview = (overview: WorldOverview) => invoke<WorldOverview>("save_world_overview", { overview });
