import { invoke } from "@tauri-apps/api/core";
import type { AiConversation, AppConfig, BootstrapData, CatalogueResource, CharacterCardV3Data, CharacterDraft, CoverImage, CreateResourceInput, DraftSaveOutcome, LinkableLorebook, LorebookData, LorebookDraft, LorebookReference, ResourceList, ResourceSaveOutcome, SelectedResource, SendAiMessageInput, WorldOverview } from "./types";
export const loadBootstrap = () => invoke<BootstrapData>("load_bootstrap");
export const saveConfiguration = (config: AppConfig) => invoke<AppConfig>("save_configuration", { config });
export const listOwnedResources = (resourceType: CreateResourceInput["resourceType"]) => invoke<ResourceList>("list_owned_resources", { resourceType });
export const fetchCharacterCover = (resourceId: string) => invoke<CoverImage | null>("fetch_character_cover", { resourceId });
export const fetchImageContent = (imageResourceId: string) => invoke<CoverImage>("fetch_image_content", { imageResourceId });
export const listOwnedImages = () => invoke<ResourceList>("list_owned_images");
export const uploadResourceCover = (resourceId: string, fileName: string, mediaType: string, bytes: number[]) => invoke<CatalogueResource>("upload_resource_cover", { resourceId, fileName, mediaType, bytes });
export const selectResourceCover = (resourceId: string, imageResourceId: string) => invoke<CatalogueResource>("select_resource_cover", { resourceId, imageResourceId });
export const listLinkableLorebooks = () => invoke<LinkableLorebook[]>("list_linkable_lorebooks");
export const saveLinkedLorebooks = (resourceId: string, linkedLorebooks: LorebookReference[], expectedRevision: number) => invoke<ResourceSaveOutcome>("save_linked_lorebooks", { resourceId, linkedLorebooks, expectedRevision });
export const selectResource = (resourceId: string, resourceType: CreateResourceInput["resourceType"]) => invoke<SelectedResource>("select_resource", { resourceId, resourceType });
export const createResource = (input: CreateResourceInput) => invoke<SelectedResource>("create_resource", { input });
export const saveCharacterDraft = (resourceId: string, data: CharacterCardV3Data, expectedRevision: number) => invoke<DraftSaveOutcome<CharacterDraft>>("save_character_draft", { resourceId, data, expectedRevision });
export const saveLorebookDraft = (resourceId: string, data: LorebookData, expectedRevision: number) => invoke<DraftSaveOutcome<LorebookDraft>>("save_lorebook_draft", { resourceId, data, expectedRevision });
export const listAiConversations = (resourceId: string | null) => invoke<AiConversation[]>("list_ai_conversations", { resourceId });
export const deleteAiConversation = (conversationId: string) => invoke<void>("delete_ai_conversation", { conversationId });
export const sendAiMessage = (input: SendAiMessageInput) => invoke<AiConversation>("send_ai_message", { input });
export const loadWorldOverview = (resourceId: string) => invoke<WorldOverview>("load_world_overview", { resourceId });
export const saveWorldOverview = (overview: WorldOverview) => invoke<WorldOverview>("save_world_overview", { overview });
