import { useMemo, useState } from "react";
import type { MessageKey } from "./i18n";
import type { CharacterCardV3Data, CharacterRegexScript, CharacterScript, EditorContext, JsonValue, SelectedCharacter } from "./types";
import "./ExtensionsPage.css";

type Tab = "regex" | "scripts" | "variables";
const uid = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const blankRegex = (): CharacterRegexScript => ({ id: uid(), scriptName: "", findRegex: "", replaceString: "", trimStrings: [], placement: [2], disabled: false, markdownOnly: false, promptOnly: false, runOnEdit: false, substituteRegex: 0, minDepth: null, maxDepth: null });
const blankScript = (): CharacterScript => ({ type: "script", enabled: true, name: "", id: uid(), content: "", info: "", button: { enabled: false, buttons: [] }, data: {} });
const parseRegex = (pattern: string) => { const literal = pattern.startsWith("/") ? pattern.match(/^\/(.*)\/([a-z]*)$/s) : null; return new RegExp(literal ? literal[1] : pattern, literal ? literal[2] : "g"); };
const valueText = (value: JsonValue) => typeof value === "string" ? value : JSON.stringify(value);
const parseValue = (value: string): JsonValue => { try { return JSON.parse(value) as JsonValue; } catch { return value; } };
const valueForType = (type: string): JsonValue => type === "number" ? 0 : type === "boolean" ? false : type === "array" ? [] : type === "object" ? {} : type === "null" ? null : "";

export function ExtensionsPage({ selected, dirty, status, onChange, onContext, onSave, t }: {
  selected: SelectedCharacter;
  dirty: boolean;
  status: "idle" | "saving" | "saved" | "error";
  onChange: (value: CharacterCardV3Data) => void;
  onContext: (context: EditorContext) => void;
  onSave: () => void;
  t: (key: MessageKey) => string;
}) {
  const [tab, setTab] = useState<Tab>("regex");
  const [selectedRegex, setSelectedRegex] = useState(0);
  const [selectedScript, setSelectedScript] = useState(0);
  const [sample, setSample] = useState("");
  const [pendingDelete, setPendingDelete] = useState<{ kind: "regex" | "script" | "variable"; value: number | string } | null>(null);
  const card = selected.draft?.data;
  const regexes = card?.extensions.regex_scripts ?? [];
  const helper = card?.extensions.tavern_helper ?? { scripts: [], variables: {} };
  const scripts = helper.scripts ?? [];
  const currentRegex = regexes[selectedRegex] ?? null;
  const currentScript = scripts[selectedScript] ?? null;
  const regexResult = useMemo(() => { if (!currentRegex?.findRegex) return { output: sample, error: "" }; try { return { output: sample.replace(parseRegex(currentRegex.findRegex), currentRegex.replaceString), error: "" }; } catch (error) { return { output: sample, error: error instanceof Error ? error.message : String(error) }; } }, [currentRegex, sample]);
  if (!card) return <section className="extensions-page"><h1>{t("extensionsAndScripts")}</h1><p>{t("noDraftOverview")}</p></section>;
  const changeExtensions = (extensions: CharacterCardV3Data["extensions"]) => onChange({ ...card, extensions });
  const changeRegexes = (next: CharacterRegexScript[]) => changeExtensions({ ...card.extensions, regex_scripts: next });
  const changeHelper = (next: typeof helper) => changeExtensions({ ...card.extensions, tavern_helper: next });
  const patchRegex = <K extends keyof CharacterRegexScript>(key: K, value: CharacterRegexScript[K]) => changeRegexes(regexes.map((item, index) => index === selectedRegex ? { ...item, [key]: value } : item));
  const patchScript = <K extends keyof CharacterScript>(key: K, value: CharacterScript[K]) => changeHelper({ ...helper, scripts: scripts.map((item, index) => index === selectedScript ? { ...item, [key]: value } : item) });
  const move = <T,>(items: T[], index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next; };
  return <section className="extensions-page">
    <header className="extensions-heading"><div><p>{selected.resource.metadata.name}</p><h1>{t("extensionsAndScripts")}</h1><span>{t("extensionsIntro")}</span></div><aside role="note"><strong>{t("executableContent")}</strong><p>{t("scriptSafetyNotice")}</p></aside></header>
    <div className="extension-tabs" role="tablist">{(["regex", "scripts", "variables"] as Tab[]).map((value) => <button role="tab" aria-selected={tab === value} className={tab === value ? "active" : ""} onClick={() => setTab(value)} key={value}>{t(value === "regex" ? "regexScripts" : value === "scripts" ? "characterScripts" : "runtimeVariables")}</button>)}</div>
    {tab === "regex" && <div className="extension-workspace"><CollectionList title={t("regexScripts")} items={regexes.map((item, index) => item.scriptName || `${t("regexScript")} ${index + 1}`)} selected={selectedRegex} onSelect={setSelectedRegex} onAdd={() => { changeRegexes([...regexes, blankRegex()]); setSelectedRegex(regexes.length); }} onMove={(direction) => { changeRegexes(move(regexes, selectedRegex, direction)); setSelectedRegex(Math.max(0, Math.min(regexes.length - 1, selectedRegex + direction))); }} onDelete={() => setPendingDelete({ kind: "regex", value: selectedRegex })} t={t} />
      <section className="extension-editor">{currentRegex ? <><div className="extension-form"><label>{t("scriptName")}<input value={currentRegex.scriptName} onChange={(event) => patchRegex("scriptName", event.target.value)} /></label><label className="toggle"><input type="checkbox" checked={!currentRegex.disabled} onChange={(event) => patchRegex("disabled", !event.target.checked)} />{t("enabled")}</label><label className="wide">{t("findPattern")}<textarea rows={4} value={currentRegex.findRegex} onFocus={() => onContext({ path: `extensions.regex_scripts.${selectedRegex}.findRegex`, selectedText: currentRegex.findRegex, cursor: null })} onChange={(event) => patchRegex("findRegex", event.target.value)} /></label><label className="wide">{t("replacement")}<textarea rows={4} value={currentRegex.replaceString} onFocus={() => onContext({ path: `extensions.regex_scripts.${selectedRegex}.replaceString`, selectedText: currentRegex.replaceString, cursor: null })} onChange={(event) => patchRegex("replaceString", event.target.value)} /></label><div className="extension-checks wide"><label><input type="checkbox" checked={currentRegex.markdownOnly} onChange={(event) => patchRegex("markdownOnly", event.target.checked)} />{t("displayOnly")}</label><label><input type="checkbox" checked={currentRegex.promptOnly} onChange={(event) => patchRegex("promptOnly", event.target.checked)} />{t("promptOnly")}</label><label><input type="checkbox" checked={currentRegex.runOnEdit} onChange={(event) => patchRegex("runOnEdit", event.target.checked)} />{t("runOnEdit")}</label></div><label>{t("minimumDepth")}<input type="number" value={currentRegex.minDepth ?? ""} onChange={(event) => patchRegex("minDepth", event.target.value === "" ? null : Number(event.target.value))} /></label><label>{t("maximumDepth")}<input type="number" value={currentRegex.maxDepth ?? ""} onChange={(event) => patchRegex("maxDepth", event.target.value === "" ? null : Number(event.target.value))} /></label></div><div className="regex-test"><h2>{t("regexTestBench")}</h2><div><label>{t("sampleInput")}<textarea rows={7} value={sample} onChange={(event) => setSample(event.target.value)} /></label><label>{t("transformedOutput")}<textarea rows={7} readOnly value={regexResult.error || regexResult.output} /></label></div>{regexResult.error && <p role="alert">{regexResult.error}</p>}</div></> : <EmptyCollection onAdd={() => { changeRegexes([blankRegex()]); setSelectedRegex(0); }} label={t("addRegexScript")} />}</section></div>}
    {tab === "scripts" && <div className="extension-workspace"><CollectionList title={t("characterScripts")} items={scripts.map((item, index) => item.name || `${t("characterScript")} ${index + 1}`)} selected={selectedScript} onSelect={setSelectedScript} onAdd={() => { changeHelper({ ...helper, scripts: [...scripts, blankScript()] }); setSelectedScript(scripts.length); }} onMove={(direction) => { changeHelper({ ...helper, scripts: move(scripts, selectedScript, direction) }); setSelectedScript(Math.max(0, Math.min(scripts.length - 1, selectedScript + direction))); }} onDelete={() => setPendingDelete({ kind: "script", value: selectedScript })} t={t} />
      <section className="extension-editor">{currentScript ? <div className="extension-form"><label>{t("scriptName")}<input value={currentScript.name} onChange={(event) => patchScript("name", event.target.value)} /></label><label className="toggle"><input type="checkbox" checked={currentScript.enabled} onChange={(event) => patchScript("enabled", event.target.checked)} />{t("enabled")}</label><label className="wide">{t("scriptDescription")}<textarea rows={3} value={currentScript.info} onChange={(event) => patchScript("info", event.target.value)} /></label><label className="wide">{t("scriptSource")}<textarea className="code-input" rows={22} spellCheck={false} value={currentScript.content} onFocus={() => onContext({ path: `extensions.tavern_helper.scripts.${selectedScript}.content`, selectedText: currentScript.content, cursor: null })} onChange={(event) => patchScript("content", event.target.value)} /></label><label className="toggle wide"><input type="checkbox" checked={currentScript.button?.enabled ?? false} onChange={(event) => patchScript("button", { ...(currentScript.button ?? { buttons: [] }), enabled: event.target.checked })} />{t("scriptButtonsEnabled")}</label></div> : <EmptyCollection onAdd={() => { changeHelper({ ...helper, scripts: [blankScript()] }); setSelectedScript(0); }} label={t("addCharacterScript")} />}</section></div>}
    {tab === "variables" && <section className="variables-editor"><header><div><h2>{t("runtimeVariables")}</h2><p>{t("runtimeVariablesHint")}</p></div><button className="primary" onClick={() => { let name = "variable"; let suffix = 1; while (Object.hasOwnProperty.call(helper.variables, name)) name = `variable${++suffix}`; changeHelper({ ...helper, variables: { ...helper.variables, [name]: "" } }); }}>{t("addVariable")}</button></header><div className="variable-table">{Object.entries(helper.variables).map(([name, value]) => <div key={name}><input aria-label={t("variableName")} value={name} onChange={(event) => { const next = { ...helper.variables }; delete next[name]; next[event.target.value] = value; changeHelper({ ...helper, variables: next }); }} /><select aria-label={t("variableType")} value={Array.isArray(value) ? "array" : value === null ? "null" : typeof value} onChange={(event) => changeHelper({ ...helper, variables: { ...helper.variables, [name]: valueForType(event.target.value) } })}><option value="string">{t("textType")}</option><option value="number">{t("numberType")}</option><option value="boolean">{t("booleanType")}</option><option value="array">{t("arrayType")}</option><option value="object">{t("objectType")}</option><option value="null">null</option></select><input aria-label={t("initialValue")} value={valueText(value)} onChange={(event) => changeHelper({ ...helper, variables: { ...helper.variables, [name]: parseValue(event.target.value) } })} /><button className="danger-outline" onClick={() => setPendingDelete({ kind: "variable", value: name })}>{t("remove")}</button></div>)}</div>{Object.keys(helper.variables).length === 0 && <p className="variables-empty">{t("noRuntimeVariables")}</p>}<aside><strong>{t("mvuCompatibility")}</strong><p>{t("mvuCompatibilityHint")}</p><dl><div><dt>{t("characterScripts")}</dt><dd>{scripts.length}</dd></div><div><dt>{t("loreEntries")}</dt><dd>{card.character_book?.entries.length ?? 0}</dd></div><div><dt>{t("regexScripts")}</dt><dd>{regexes.length}</dd></div></dl></aside></section>}
    <div className="extensions-save-bar"><span>{status === "saved" ? t("extensionsSaved") : status === "error" ? t("extensionsSaveError") : dirty ? t("unsavedChanges") : ""}</span><button className="primary" disabled={!dirty || status === "saving"} onClick={onSave}>{status === "saving" ? t("saving") : t("saveExtensions")}</button></div>
    {pendingDelete && <div className="confirmation-layer"><section className="confirmation-dialog" role="alertdialog" aria-modal="true"><h2>{t("deleteExtensionTitle")}</h2><p>{t("deleteExtensionBody")}</p><div><button className="secondary" autoFocus onClick={() => setPendingDelete(null)}>{t("cancel")}</button><button className="danger-button" onClick={() => { if (pendingDelete.kind === "regex") { const index = Number(pendingDelete.value); changeRegexes(regexes.filter((_, itemIndex) => itemIndex !== index)); setSelectedRegex(Math.max(0, index - 1)); } else if (pendingDelete.kind === "script") { const index = Number(pendingDelete.value); changeHelper({ ...helper, scripts: scripts.filter((_, itemIndex) => itemIndex !== index) }); setSelectedScript(Math.max(0, index - 1)); } else { const next = { ...helper.variables }; delete next[String(pendingDelete.value)]; changeHelper({ ...helper, variables: next }); } setPendingDelete(null); }}>{t("remove")}</button></div></section></div>}
  </section>;
}

function CollectionList({ title, items, selected, onSelect, onAdd, onMove, onDelete, t }: { title: string; items: string[]; selected: number; onSelect: (index: number) => void; onAdd: () => void; onMove: (direction: -1 | 1) => void; onDelete: () => void; t: (key: MessageKey) => string }) {
  return <aside className="extension-list"><header><h2>{title}</h2><button className="primary" onClick={onAdd}>＋</button></header><div>{items.map((item, index) => <button className={selected === index ? "active" : ""} key={`${item}-${index}`} onClick={() => onSelect(index)}><strong>{item}</strong><small>{index + 1}</small></button>)}</div>{items.length > 0 && <footer><button onClick={() => onMove(-1)} disabled={selected === 0}>{t("moveUp")}</button><button onClick={() => onMove(1)} disabled={selected === items.length - 1}>{t("moveDown")}</button><button className="danger-outline" onClick={onDelete}>{t("remove")}</button></footer>}</aside>;
}
function EmptyCollection({ onAdd, label }: { onAdd: () => void; label: string }) { return <div className="extension-empty"><p>—</p><button className="primary" onClick={onAdd}>{label}</button></div>; }
