import type { Locale } from "./types";

const en = {
  resources: "Resources", settings: "Settings", overview: "Overview", appName: "RolePlay Catalogue Client",
  worldOverview: "World overview", worldOverviewTitle: "World overview", worldOverviewIntro: "Establish the shared setting and intended roleplay experience before writing card fields.", worldOverviewLocal: "Stored locally for this resource and never sent to the catalogue.",
  chooseTitle: "Choose a character", chooseIntro: "Select an owned character card or create one.", create: "Create character", refresh: "Refresh", noResources: "No character cards found.", loading: "Loading…", select: "Select", selected: "Selected",
  newCharacter: "New character", name: "Name", description: "Description", tags: "Tags", tagsHint: "Separate tags with commas.", visibility: "Visibility", private: "Private", authenticated: "Authenticated users", public: "Public", cancel: "Cancel", creating: "Creating…", createAction: "Create and select",
  resourceError: "Could not load catalogue resources.", configureCatalogue: "Configure the catalogue URL and API key in Settings.", draftMissing: "No draft data",
  settingsTitle: "Settings", settingsIntro: "Configure local AI and catalogue connections.", llm: "LLM provider", provider: "Provider", baseUrl: "Base URL", apiKey: "API credential", apiKeyHint: "Stored locally in the application configuration.", showKey: "Show credential", hideKey: "Hide credential", model: "Model name", contextWindow: "Context window", maxOutput: "Maximum output tokens", temperature: "Temperature", catalogue: "Catalogue", locale: "Language", save: "Save settings", saving: "Saving…", saved: "Settings saved", saveError: "Could not save settings.", openSettings: "Open settings",
  openNav: "Open navigation", closeNav: "Close navigation", collapseNav: "Collapse navigation", expandNav: "Expand navigation",
  openAssistant: "Open assistant", closeAssistant: "Close assistant", collapseAssistant: "Collapse assistant", expandAssistant: "Expand assistant", assistant: "Co-author", newChat: "New conversation", deleteChat: "Delete conversation", chatEmpty: "Ask for ideas, critique, or a proposed revision.", chatPlaceholder: "Write a message…", send: "Send", sending: "Sending…", providerNeeded: "Configure an LLM provider to start a conversation.", entireDraft: "Entire draft", currentContext: "Current context", applyProposal: "Accept proposal", proposalApplied: "Accepted", proposedChange: "Proposed change", noContext: "No field selected",
  deleteChatTitle: "Delete conversation?", deleteChatBody: "This removes the conversation and all of its messages from this device. This action cannot be undone.", deleting: "Deleting…",
  overviewTitle: "Character overview", overviewIntro: "Review the current working draft, its completeness, and approximate size.", completion: "Completion", fieldsFilled: "Fields filled", approximateTokens: "Approx. tokens", loreEntries: "Lore entries", loreTypes: "Lore types", fieldStatus: "Core fields", filled: "Filled", empty: "Empty", estimateDisclaimer: "Token counts are a model-independent estimate for comparison, not an exact tokenizer result.", selectForAssistant: "Select for assistant context", collectionStats: "Collections", alternateGreetings: "Alternate greetings", regexScripts: "Regex scripts", characterScripts: "Character scripts", noDraftOverview: "This resource does not currently have draft data.", changeResource: "Change resource",
  personality: "Personality", scenario: "Scenario", firstMessage: "First message", exampleDialogue: "Example dialogue", creatorNotes: "Creator notes", systemPrompt: "System prompt", postHistory: "Post-history instructions", creator: "Creator", characterVersion: "Character version",
  worldTags: "Setting tags", worldTagsHint: "Choose common tags or add your own.", customTag: "Custom tag", addTag: "Add tag", removeTag: "Remove tag", worldSummary: "World premise", worldSummaryHint: "A concise account of where and when the story occurs, what makes the world distinctive, and what is currently changing.", worldTone: "Tone and atmosphere", worldToneHint: "Emotional register, genre expectations, and the balance between hope, danger, humour, or seriousness.", worldThemes: "Themes", worldThemesHint: "Ideas the roleplay should explore without prescribing a conclusion.", worldRules: "Core rules", worldRulesHint: "Non-negotiable facts, limitations, costs, taboos, and causal rules that keep the setting coherent.", worldSociety: "Society and culture", worldSocietyHint: "Important groups, institutions, customs, social tensions, and everyday life.", worldTechnologyMagic: "Technology and supernatural systems", worldTechnologyMagicHint: "Capabilities, access, limits, costs, and how these systems affect ordinary people.", worldHistory: "Relevant history", worldHistoryHint: "Only the past events necessary to understand the present situation.", worldConflicts: "Active conflicts", worldConflictsHint: "Pressures, factions, mysteries, and unresolved problems that can produce scenes.", worldUserRole: "Role of {{user}}", worldUserRoleHint: "What the player is assumed to be, know, control, and remain free to decide.", worldExperience: "Intended experience", worldExperienceHint: "What the author wants the player to feel and do during a typical session.", worldConstraints: "Creative constraints and boundaries", worldConstraintsHint: "Required elements, exclusions, content boundaries, and facts that must remain ambiguous.", saveWorldOverview: "Save world overview", worldOverviewSaved: "World overview saved", worldOverviewError: "Could not save the world overview.", draftWorldWithAssistant: "Draft with co-author", draftWorldPrompt: "Draft a coherent world overview from the existing card and any planning notes. Preserve what is already specified, identify assumptions in your reply, and propose complete replacements only for useful worldOverview fields.", backToResources: "Back to resources",
  characterStructure: "Character structure", characterStructureHint: "Choose how the card distributes narrative control. This guides planning and co-author suggestions without changing the V3 schema.", fixedSingle: "Fixed one character", fixedSingleDescription: "{{char}} is one predefined character with a stable identity and voice.", fixedSingleFocus: "Define voice and behaviour; relationship to {{user}}; personal knowledge and limits; situations that reveal the character.", fixedEnsemble: "Fixed multiple characters", fixedEnsembleDescription: "The card contains a known cast whose identities and relationships are established in advance.", fixedEnsembleFocus: "Define each cast member; relationships and tensions; speaker clarity; who enters each scene; shared narration rules.", dynamicEnsemble: "Dynamic multiple characters", dynamicEnsembleDescription: "The card runs a world or scenario that can introduce new characters according to authored rules.", dynamicEnsembleFocus: "Define generation boundaries; recurring roles and factions; continuity rules; scene population; player agency and narrator authority.", templateFocus: "Planning focus",
} as const;

const zh: Record<keyof typeof en, string> = {
  resources: "资源", settings: "设置", overview: "概览", appName: "RolePlay Catalogue Client",
  worldOverview: "世界观设定", worldOverviewTitle: "世界观设定", worldOverviewIntro: "在编写角色卡字段前，先明确共同世界、创作方向与预期体验。", worldOverviewLocal: "此内容仅按当前资源保存在本机，不会发送到目录服务。",
  chooseTitle: "选择角色", chooseIntro: "选择已有角色卡，或创建一个新角色。", create: "创建角色", refresh: "刷新", noResources: "没有找到角色卡。", loading: "正在加载…", select: "选择", selected: "已选择",
  newCharacter: "新建角色", name: "名称", description: "描述", tags: "标签", tagsHint: "使用逗号分隔标签。", visibility: "可见性", private: "私有", authenticated: "已登录用户", public: "公开", cancel: "取消", creating: "正在创建…", createAction: "创建并选择",
  resourceError: "无法加载目录资源。", configureCatalogue: "请在设置中配置目录服务 URL 和 API 密钥。", draftMissing: "没有草稿数据",
  settingsTitle: "设置", settingsIntro: "配置本地 AI 与目录服务连接。", llm: "大语言模型服务", provider: "服务商", baseUrl: "基础 URL", apiKey: "API 凭据", apiKeyHint: "凭据保存在本机应用配置中。", showKey: "显示凭据", hideKey: "隐藏凭据", model: "模型名称", contextWindow: "上下文窗口", maxOutput: "最大输出 Token", temperature: "温度", catalogue: "目录服务", locale: "界面语言", save: "保存设置", saving: "保存中…", saved: "设置已保存", saveError: "无法保存设置。", openSettings: "打开设置",
  openNav: "打开导航", closeNav: "关闭导航", collapseNav: "收起导航", expandNav: "展开导航",
  openAssistant: "打开助手", closeAssistant: "关闭助手", collapseAssistant: "收起助手", expandAssistant: "展开助手", assistant: "共同创作", newChat: "新对话", deleteChat: "删除对话", chatEmpty: "询问灵感、审阅意见，或让助手提出修改方案。", chatPlaceholder: "输入消息…", send: "发送", sending: "发送中…", providerNeeded: "请先配置大语言模型服务。", entireDraft: "完整草稿", currentContext: "当前上下文", applyProposal: "接受方案", proposalApplied: "已接受", proposedChange: "修改方案", noContext: "未选择字段",
  deleteChatTitle: "删除对话？", deleteChatBody: "这会从本机删除该对话及其全部消息，且无法撤销。", deleting: "正在删除…",
  overviewTitle: "角色概览", overviewIntro: "查看当前工作草稿的完整度和大致篇幅。", completion: "完成度", fieldsFilled: "已填写字段", approximateTokens: "估算 Token", loreEntries: "世界书条目", loreTypes: "条目类型", fieldStatus: "核心字段", filled: "已填写", empty: "未填写", estimateDisclaimer: "Token 数量采用与模型无关的近似估算，仅用于比较，并非精确分词结果。", selectForAssistant: "设为助手上下文", collectionStats: "集合", alternateGreetings: "备用开场白", regexScripts: "正则脚本", characterScripts: "角色脚本", noDraftOverview: "此资源目前没有草稿数据。", changeResource: "更换资源",
  personality: "性格", scenario: "场景", firstMessage: "开场白", exampleDialogue: "示例对话", creatorNotes: "创作者备注", systemPrompt: "系统提示词", postHistory: "历史后指令", creator: "创作者", characterVersion: "角色版本",
  worldTags: "题材标签", worldTagsHint: "选择常用标签，或添加自定义标签。", customTag: "自定义标签", addTag: "添加标签", removeTag: "移除标签", worldSummary: "世界前提", worldSummaryHint: "简要说明故事发生的时空、世界的独特之处，以及当下正在发生的变化。", worldTone: "基调与氛围", worldToneHint: "情绪基调、类型预期，以及希望、危险、幽默或严肃之间的平衡。", worldThemes: "主题", worldThemesHint: "希望角色扮演探索的观念，但不预设结论。", worldRules: "核心规则", worldRulesHint: "维持设定自洽所需的事实、限制、代价、禁忌和因果规则。", worldSociety: "社会与文化", worldSocietyHint: "重要群体、制度、习俗、社会矛盾与日常生活。", worldTechnologyMagic: "科技与超自然体系", worldTechnologyMagicHint: "能力、获取方式、限制、代价，以及这些体系对普通人的影响。", worldHistory: "相关历史", worldHistoryHint: "只记录理解当前局势所必需的过去事件。", worldConflicts: "当前冲突", worldConflictsHint: "能够推动场景的压力、阵营、谜团与未解决问题。", worldUserRole: "{{user}} 的角色", worldUserRoleHint: "玩家被假定是什么身份、知道什么、能控制什么，以及必须保留哪些决定权。", worldExperience: "预期体验", worldExperienceHint: "作者希望玩家在典型会话中感受什么、做什么。", worldConstraints: "创作约束与边界", worldConstraintsHint: "必需元素、排除项、内容边界，以及必须保持模糊的事实。", saveWorldOverview: "保存世界观设定", worldOverviewSaved: "世界观设定已保存", worldOverviewError: "无法保存世界观设定。", draftWorldWithAssistant: "与共同创作者起草", draftWorldPrompt: "请根据现有角色卡和规划笔记，起草一份自洽的世界观设定。保留已经明确的内容，在回复中说明你的假设，并只为有用的 worldOverview 字段提出完整替换方案。", backToResources: "返回资源选择",
  characterStructure: "角色结构", characterStructureHint: "选择角色卡如何分配叙事控制权。此选择用于规划和共同创作建议，不会改变 V3 数据结构。", fixedSingle: "固定单角色", fixedSingleDescription: "{{char}} 是一个身份与说话方式稳定的预设角色。", fixedSingleFocus: "明确语言与行为、与 {{user}} 的关系、个人知识与边界，以及能展现角色的情境。", fixedEnsemble: "固定多角色", fixedEnsembleDescription: "角色卡包含一组预先确定身份和关系的固定角色。", fixedEnsembleFocus: "明确每位角色、彼此关系与矛盾、发言辨识、角色出场条件，以及共同叙事规则。", dynamicEnsemble: "动态多角色", dynamicEnsembleDescription: "角色卡负责运行世界或场景，并按创作规则引入新角色。", dynamicEnsembleFocus: "明确生成边界、常见角色与阵营、连续性规则、场景人口，以及玩家自主权和叙述者权限。", templateFocus: "规划重点",
};

const messages = { "en-GB": en, "zh-CN": zh } as const;
export type MessageKey = keyof typeof en;
export const translate = (locale: Locale, key: MessageKey) => messages[locale][key];
