import { useMemo, useState } from "react";
import type { MessageKey } from "./i18n";
import { estimateTokens } from "./OverviewPage";
import type { EditorContext, JsonValue, PresetData, PresetPrompt, SelectedPreset } from "./types";
import "./PresetEditorPage.css";

const samplers = ["temperature", "frequency_penalty", "presence_penalty", "top_p", "top_k", "top_a", "min_p", "repetition_penalty", "openai_max_context", "openai_max_tokens", "seed", "n"] as const;
const known = new Set<string>([...samplers, "stream_openai", "prompts", "prompt_order"]);
const id = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const promptTokens = (prompt: PresetPrompt) => estimateTokens(typeof prompt.content === "string" ? prompt.content : "");
const parseValue = (text: string): JsonValue => { try { return JSON.parse(text) as JsonValue; } catch { return text; } };

export function PresetEditorPage({ selected, dirty, status, onChange, onContext, onDraft, onSave, t }: {
  selected: SelectedPreset;
  dirty: boolean;
  status: "idle" | "saving" | "saved" | "error";
  onChange: (data: PresetData) => void;
  onContext: (context: EditorContext) => void;
  onDraft: () => void;
  onSave: () => void;
  t: (key: MessageKey) => string;
}) {
  const data = selected.draft?.data;
  const prompts = data?.prompts ?? [];
  const [selectedId, setSelectedId] = useState<string | null>(prompts[0]?.identifier ?? null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [newParameter, setNewParameter] = useState("");
  const selectedIndex = prompts.findIndex((prompt) => prompt.identifier === selectedId);
  const prompt = selectedIndex >= 0 ? prompts[selectedIndex] : null;
  const advanced = useMemo(() => Object.entries(data ?? {}).filter(([key]) => !known.has(key)), [data]);
  if (!data) return <section className="preset-page"><p>{t("noPresetDraft")}</p></section>;
  const patch = (key: string, value: PresetData[string]) => onChange({ ...data, [key]: value });
  const patchPrompt = (field: string, value: JsonValue) => { if (!prompt) return; patch("prompts", prompts.map((item, index) => index === selectedIndex ? { ...item, [field]: value } : item)); onContext({ path: `preset.prompts.${selectedIndex}.${field}`, selectedText: typeof value === "string" ? value : null, cursor: null }); };
  const addPrompt = () => { const identifier = `custom-${id()}`; const next: PresetPrompt = { identifier, name: "", role: "system", marker: false, system_prompt: false, content: "" }; const prompt_order = data.prompt_order?.length ? data.prompt_order.map((group) => ({ ...group, order: [...group.order, { identifier, enabled: true }] })) : [{ character_id: 100000, order: [{ identifier, enabled: true }] }]; onChange({ ...data, prompts: [...prompts, next], prompt_order }); setSelectedId(identifier); };
  const removePrompt = () => { if (!deleteId) return; onChange({ ...data, prompts: prompts.filter((item) => item.identifier !== deleteId), prompt_order: (data.prompt_order ?? []).map((group) => ({ ...group, order: group.order.filter((item) => item.identifier !== deleteId) })) }); const remaining = prompts.filter((item) => item.identifier !== deleteId); setSelectedId(remaining[0]?.identifier ?? null); setDeleteId(null); };
  const move = (direction: -1 | 1) => { const target = selectedIndex + direction; if (selectedIndex < 0 || target < 0 || target >= prompts.length) return; const next = [...prompts]; [next[selectedIndex], next[target]] = [next[target], next[selectedIndex]]; const rank = new Map(next.map((item, index) => [item.identifier, index])); onChange({ ...data, prompts: next, prompt_order: (data.prompt_order ?? []).map((group) => ({ ...group, order: [...group.order].sort((a, b) => (rank.get(a.identifier) ?? 9999) - (rank.get(b.identifier) ?? 9999)) })) }); };
  const enabled = prompt ? data.prompt_order?.[0]?.order.find((item) => item.identifier === prompt.identifier)?.enabled ?? true : false;
  const setEnabled = (value: boolean) => { if (!prompt) return; const groups = data.prompt_order?.length ? data.prompt_order : [{ character_id: 100000, order: prompts.map((item) => ({ identifier: item.identifier, enabled: true })) }]; patch("prompt_order", groups.map((group) => ({ ...group, order: group.order.map((item) => item.identifier === prompt.identifier ? { ...item, enabled: value } : item) }))); };
  return <section className="preset-page"><header><div><p>{selected.resource.metadata.name}</p><h1>{t("presetEditor")}</h1><span>{t("presetEditorIntro")}</span></div><button className="secondary" onClick={onDraft}>{t("draftPresetPrompt")}</button></header>
    <section className="preset-parameters"><header><div><h2>{t("samplingParameters")}</h2><p>{t("samplingParametersHint")}</p></div><div><select value={newParameter} onChange={(event) => setNewParameter(event.target.value)}><option value="">{t("chooseParameter")}</option>{samplers.filter((key) => data[key] == null).map((key) => <option key={key} value={key}>{key}</option>)}</select><button className="secondary" disabled={!newParameter} onClick={() => { patch(newParameter, newParameter.includes("context") || newParameter.includes("tokens") || newParameter === "n" ? 1 : newParameter === "seed" ? -1 : 1); setNewParameter(""); }}>{t("addParameter")}</button></div></header><div className="parameter-grid">{samplers.filter((key) => data[key] != null).map((key) => <label key={key}><span>{key}<button title={t("removeParameter")} onClick={() => { const next = { ...data }; delete next[key]; onChange(next); }}>×</button></span><input type="number" step="any" value={typeof data[key] === "number" ? data[key] : ""} onChange={(event) => patch(key, Number(event.target.value))} /></label>)}{data.stream_openai != null && <label className="parameter-boolean"><span>stream_openai<button title={t("removeParameter")} onClick={() => { const next = { ...data }; delete next.stream_openai; onChange(next); }}>×</button></span><input type="checkbox" checked={Boolean(data.stream_openai)} onChange={(event) => patch("stream_openai", event.target.checked)} /></label>}</div></section>
    <div className="preset-workspace"><aside><header><h2>{t("presetPrompts")}</h2><button className="primary" onClick={addPrompt}>{t("addPrompt")}</button></header>{prompts.map((item, index) => <button key={item.identifier} className={item.identifier === selectedId ? "active" : ""} onClick={() => { setSelectedId(item.identifier); onContext({ path: `preset.prompts.${index}.content`, selectedText: typeof item.content === "string" ? item.content : null, cursor: null }); }}><strong>{item.name || item.identifier}</strong><small>{item.role ?? "system"} · ~{promptTokens(item)}</small></button>)}</aside><section className="prompt-editor">{prompt ? <><header><div><h2>{prompt.name || prompt.identifier}</h2><small>{prompt.identifier}</small></div><div><button className="secondary" disabled={selectedIndex === 0} onClick={() => move(-1)}>↑</button><button className="secondary" disabled={selectedIndex === prompts.length - 1} onClick={() => move(1)}>↓</button><button className="danger-outline" onClick={() => setDeleteId(prompt.identifier)}>{t("remove")}</button></div></header><div className="prompt-grid"><label>{t("promptName")}<input value={prompt.name ?? ""} onChange={(event) => patchPrompt("name", event.target.value)} /></label><label>{t("promptRole")}<select value={prompt.role ?? "system"} onChange={(event) => patchPrompt("role", event.target.value)}><option value="system">system</option><option value="user">user</option><option value="assistant">assistant</option></select></label><label><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} />{t("enabled")}</label><label><input type="checkbox" checked={Boolean(prompt.marker)} onChange={(event) => patchPrompt("marker", event.target.checked)} />{t("markerPrompt")}</label><label><input type="checkbox" checked={Boolean(prompt.system_prompt)} onChange={(event) => patchPrompt("system_prompt", event.target.checked)} />{t("systemPromptFlag")}</label><label className="wide">{t("promptContent")}<textarea rows={18} disabled={Boolean(prompt.marker)} value={typeof prompt.content === "string" ? prompt.content : ""} onFocus={() => onContext({ path: `preset.prompts.${selectedIndex}.content`, selectedText: typeof prompt.content === "string" ? prompt.content : null, cursor: null })} onChange={(event) => patchPrompt("content", event.target.value)} /><small>~{promptTokens(prompt)} {t("approximateFieldTokens")}</small></label></div></> : <p>{t("selectPresetPrompt")}</p>}</section></div>
    <section className="preset-advanced"><header><div><h2>{t("providerParameters")}</h2><p>{t("providerParametersHint")}</p></div><button className="secondary" onClick={() => { let key = "custom_parameter"; let suffix = 2; while (data[key] !== undefined) key = `custom_parameter_${suffix++}`; patch(key, ""); }}>{t("addCustomParameter")}</button></header>{advanced.length ? <div>{advanced.map(([key, value]) => <article key={key}><input aria-label={t("parameterName")} value={key} onChange={(event) => { const next = { ...data }; delete next[key]; next[event.target.value] = value; onChange(next); }} /><textarea rows={2} value={JSON.stringify(value)} onChange={(event) => patch(key, parseValue(event.target.value))} /><button className="danger-outline" onClick={() => { const next = { ...data }; delete next[key]; onChange(next); }}>{t("remove")}</button></article>)}</div> : <p>{t("noProviderParameters")}</p>}</section>
    <div className="lorebook-save-bar"><span>{status === "saved" ? t("presetSaved") : status === "error" ? t("presetSaveError") : dirty ? t("unsavedChanges") : ""}</span><button className="primary" disabled={!dirty || status === "saving"} onClick={onSave}>{status === "saving" ? t("saving") : t("savePreset")}</button></div>
    {deleteId && <div className="confirmation-layer"><section className="confirmation-dialog" role="alertdialog" aria-modal="true"><h2>{t("removePresetPromptTitle")}</h2><p>{t("removePresetPromptBody")}</p><div><button className="secondary" autoFocus onClick={() => setDeleteId(null)}>{t("cancel")}</button><button className="danger-button" onClick={removePrompt}>{t("remove")}</button></div></section></div>}
  </section>;
}
