import { useEffect, useState } from "react";
import { exportResourceDraft, listResourceVersions, previewResourceDraft, publishResource, saveResourceMetadata } from "./backend";
import type { MessageKey } from "./i18n";
import { estimateTokens } from "./OverviewPage";
import type { CatalogueResource, JsonValue, PresetData, ResourceMetadata, ResourceVersionSummary, SelectedPreset } from "./types";
import "./LorebookOverviewPage.css";

const unique = (values: string[]) => [...new Set(values.map((value) => value.trim()).filter(Boolean))];
const promptContent = (data: PresetData) => (data.prompts ?? []).map((prompt) => typeof prompt.content === "string" ? prompt.content : "").join("\n");
const structuralKeys = new Set(["prompts", "prompt_order"]);

export function PresetOverviewPage({ selected, dirty, onEdit, onChangeResource, onResource, t }: {
  selected: SelectedPreset; dirty: boolean; onEdit: () => void; onChangeResource: () => void; onResource: (resource: CatalogueResource) => void; t: (key: MessageKey) => string;
}) {
  const [metadata, setMetadata] = useState<ResourceMetadata>(selected.resource.metadata);
  const [metadataStatus, setMetadataStatus] = useState<"idle" | "saving" | "saved" | "error" | "conflict">("idle");
  const [versions, setVersions] = useState<ResourceVersionSummary[]>([]);
  const [preview, setPreview] = useState<JsonValue | null>(null);
  const [releaseVersion, setReleaseVersion] = useState("");
  const [publishOpen, setPublishOpen] = useState(false);
  const [releaseStatus, setReleaseStatus] = useState<"idle" | "previewing" | "exporting" | "publishing" | "error">("idle");
  const [releaseError, setReleaseError] = useState("");
  useEffect(() => { setMetadata(selected.resource.metadata); setMetadataStatus("idle"); }, [selected.resource.id, selected.resource.revision]);
  useEffect(() => { let active = true; void listResourceVersions(selected.resource.id).then((items) => active && setVersions(items)).catch(() => undefined); return () => { active = false; }; }, [selected.resource.id]);
  const data = selected.draft?.data ?? {};
  const prompts = data.prompts ?? [];
  const enabledIds = new Set((data.prompt_order ?? []).flatMap((group) => group.order.filter((item) => item.enabled).map((item) => item.identifier)));
  const parameters = Object.entries(data).filter(([key, value]) => !structuralKeys.has(key) && value != null).length;
  const tokens = estimateTokens(promptContent(data));
  const saveMetadata = async () => { setMetadataStatus("saving"); try { const outcome = await saveResourceMetadata(selected.resource.id, metadata, selected.resource.revision); if (outcome.saved) { onResource(outcome.saved); setMetadataStatus("saved"); } else if (outcome.current) { onResource(outcome.current); setMetadata(outcome.current.metadata); setMetadataStatus("conflict"); } } catch { setMetadataStatus("error"); } };
  const loadPreview = async () => { setReleaseStatus("previewing"); setReleaseError(""); try { setPreview(await previewResourceDraft(selected.resource.id)); setReleaseStatus("idle"); } catch (error) { setReleaseError(String(error)); setReleaseStatus("error"); } };
  const exportDraft = async () => { setReleaseStatus("exporting"); setReleaseError(""); try { const artifact = await exportResourceDraft(selected.resource.id); const binary = atob(artifact.data); const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: artifact.mediaType })); const link = document.createElement("a"); link.href = url; link.download = artifact.fileName; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setReleaseStatus("idle"); } catch (error) { setReleaseError(String(error)); setReleaseStatus("error"); } };
  const publish = async () => { setReleaseStatus("publishing"); setReleaseError(""); try { const version = await publishResource(selected.resource.id, releaseVersion); setVersions((items) => [version, ...items]); setReleaseVersion(""); setPublishOpen(false); setReleaseStatus("idle"); } catch (error) { setReleaseError(String(error)); setReleaseStatus("error"); } };
  const previewData = preview && typeof preview === "object" && !Array.isArray(preview) ? preview as Record<string, JsonValue> : null;
  const previewPrompts = Array.isArray(previewData?.prompts) ? previewData.prompts : [];
  return <section className="lorebook-overview"><header><div><p>{selected.resource.metadata.name}</p><h1>{t("presetOverview")}</h1><span>{t("presetOverviewIntro")}</span></div><div><button className="secondary" onClick={onChangeResource}>{t("changeResource")}</button><button className="primary" onClick={onEdit}>{t("editPreset")}</button></div></header>
    <div className="metric-grid"><article><span>{t("presetPrompts")}</span><strong>{prompts.length}</strong></article><article><span>{t("enabledPrompts")}</span><strong>{enabledIds.size || prompts.length}</strong></article><article><span>{t("samplingAndProviderParameters")}</span><strong>{parameters}</strong></article><article><span>{t("approximateTokens")}</span><strong>{tokens.toLocaleString()}</strong></article></div><p className="estimate-note">{t("presetNoCompleteness")}</p>
    <section className="review-panel"><header><div><h2>{t("promptComposition")}</h2><p>{t("promptCompositionHint")}</p></div></header><div className="review-issues">{prompts.map((prompt, index) => <button key={prompt.identifier} onClick={onEdit}><span className="review-severity">{index + 1}</span><span><strong>{prompt.name || prompt.identifier}</strong><small>{prompt.role ?? "system"} · ~{estimateTokens(typeof prompt.content === "string" ? prompt.content : "")}</small></span><em>{prompt.marker ? t("markerPrompt") : enabledIds.size === 0 || enabledIds.has(prompt.identifier) ? t("enabled") : t("disabled")}</em></button>)}</div>{prompts.length === 0 && <div className="review-ready"><strong>{t("noPresetPrompts")}</strong><p>{t("emptyPresetValid")}</p></div>}</section>
    <section className="review-panel metadata-panel"><header><div><h2>{t("resourceMetadataTitle")}</h2><p>{t("resourceMetadataHint")}</p></div></header><div className="lorebook-metadata-grid"><label>{t("name")}<input value={metadata.name} onChange={(event) => setMetadata({ ...metadata, name: event.target.value })} /></label><label>{t("contentLanguage")}<select value={metadata.language} onChange={(event) => setMetadata({ ...metadata, language: event.target.value as ResourceMetadata["language"] })}><option value="en-uk">{t("languageEnUK")}</option><option value="zh-cn">{t("languageZhCN")}</option></select></label><label>{t("visibility")}<select value={metadata.visibility} onChange={(event) => setMetadata({ ...metadata, visibility: event.target.value as ResourceMetadata["visibility"] })}><option value="private">{t("private")}</option><option value="authenticated">{t("authenticated")}</option><option value="public">{t("public")}</option></select></label><label>{t("tags")}<input value={metadata.tags.join(", ")} onChange={(event) => setMetadata({ ...metadata, tags: unique(event.target.value.split(",")) })} /></label><label className="wide">{t("description")}<textarea rows={4} value={metadata.description} onChange={(event) => setMetadata({ ...metadata, description: event.target.value })} /></label></div><footer><span>{metadataStatus === "saved" ? t("resourceMetadataSaved") : metadataStatus === "conflict" ? t("resourceMetadataConflict") : metadataStatus === "error" ? t("resourceMetadataError") : ""}</span><button className="primary" disabled={metadataStatus === "saving" || !metadata.name.trim()} onClick={() => void saveMetadata()}>{metadataStatus === "saving" ? t("saving") : t("saveResourceMetadata")}</button></footer></section>
    <section className="review-panel release-panel"><header><div><h2>{t("releaseAndExport")}</h2><p>{t("presetReleaseHint")}</p></div><div className="release-actions"><button className="secondary" disabled={dirty || releaseStatus !== "idle"} onClick={() => void loadPreview()}>{releaseStatus === "previewing" ? t("previewing") : t("previewPreset")}</button><button className="secondary" disabled={dirty || releaseStatus !== "idle"} onClick={() => void exportDraft()}>{releaseStatus === "exporting" ? t("exporting") : t("exportDraft")}</button><button className="primary" disabled={dirty || releaseStatus !== "idle" || !selected.draft} onClick={() => setPublishOpen(true)}>{t("publishRelease")}</button></div></header>{dirty && <p className="release-blocker">{t("unsavedReleaseBlock")}</p>}{releaseError && <p className="release-blocker">{releaseError}</p>}<div className="collection-list"><div><dt>{t("publishedReleases")}</dt><dd>{versions.length}</dd></div>{versions[0] && <div><dt>{t("latestRelease")}</dt><dd>{versions[0].version}</dd></div>}</div></section>
    {previewData && <div className="confirmation-layer" onMouseDown={(event) => event.target === event.currentTarget && setPreview(null)}><section className="confirmation-dialog lorebook-preview" role="dialog" aria-modal="true"><h2>{t("presetPreview")}</h2><p>{t("presetPreviewHint")}</p>{previewPrompts.map((raw, index) => { const prompt = raw && typeof raw === "object" && !Array.isArray(raw) ? raw as Record<string, JsonValue> : {}; return <article key={index}><strong>{String(prompt.name ?? prompt.identifier ?? `${t("presetPrompts")} ${index + 1}`)}</strong><small>{String(prompt.role ?? "system")}</small><p>{String(prompt.content ?? "")}</p></article>; })}<footer><button className="primary" onClick={() => setPreview(null)}>{t("close")}</button></footer></section></div>}
    {publishOpen && <div className="confirmation-layer"><section className="confirmation-dialog" role="dialog" aria-modal="true"><h2>{t("publishRelease")}</h2><p>{t("publishReleaseHint")}</p><label>{t("releaseVersionLabel")}<input autoFocus value={releaseVersion} onChange={(event) => setReleaseVersion(event.target.value)} /></label><div><button className="secondary" onClick={() => setPublishOpen(false)}>{t("cancel")}</button><button className="primary" disabled={!releaseVersion.trim() || releaseStatus === "publishing"} onClick={() => void publish()}>{releaseStatus === "publishing" ? t("publishing") : t("publishRelease")}</button></div></section></div>}
  </section>;
}
