import { useMemo, useState } from "react";
import type { MessageKey } from "./i18n";
import type { EditorContext, JsonValue, SelectedWorld, WorldBundleData } from "./types";
import "./WorldBundlePage.css";

export const WORLD_SECTIONS = ["locations", "landmarks", "characters", "background_characters", "items", "item_stacks", "equipment", "containers", "turns", "events", "memories", "intents", "entity_relationships", "subjective_entity_claims", "entity_variable_sets"] as const;
export const WORLD_CONFIGS = ["chat", "embed", "image", "tts"] as const;
export type WorldPageKey = "world-overview" | "world-details" | `world-section:${typeof WORLD_SECTIONS[number]}` | `world-config:${typeof WORLD_CONFIGS[number]}` | "world-prompts" | "world-workflows" | "world-media";
type T = (key: MessageKey) => string;
const humanise = (key: string) => key.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const sectionKeys: Record<string, MessageKey> = { locations: "wseLocations", landmarks: "wseLandmarks", characters: "wseCharacters", background_characters: "wseBackgroundCharacters", items: "wseItems", item_stacks: "wseItemStacks", equipment: "wseEquipment", containers: "wseContainers", turns: "wseTurns", events: "wseEvents", memories: "wseMemories", intents: "wseIntents", entity_relationships: "wseRelationships", subjective_entity_claims: "wseClaims", entity_variable_sets: "wseVariables" };
const singularKeys: Record<string, MessageKey> = { locations: "wseLocation", landmarks: "wseLandmark", characters: "wseCharacter", background_characters: "wseBackgroundCharacter", items: "wseItem", item_stacks: "wseItemStack", equipment: "wseEquipmentItem", containers: "wseContainer", turns: "wseTurn", events: "wseEvent", memories: "wseMemory", intents: "wseIntent", entity_relationships: "wseRelationship", subjective_entity_claims: "wseClaim", entity_variable_sets: "wseVariableSet" };
const fieldKeys: Record<string, MessageKey> = { id: "wseFieldId", name: "name", title: "wseFieldTitle", description: "description", creation_time: "wseFieldCreationTime", starting_time: "wseFieldStartingTime", version: "wseFieldVersion", language: "wseFieldLanguage", metadata: "metadata", url: "wseFieldUrl", content: "wseFieldContent", prompt: "wseFieldPrompt", notes: "wseFieldNotes", conditions: "wseFieldConditions", constraints: "wseFieldConstraints", type: "wseFieldType", file: "wseFieldFile", imageResourceId: "wseFieldImageResource", provider: "provider", model: "model" };
const configKeys: Record<string, MessageKey> = { chat: "wseChatConfig", embed: "wseEmbedConfig", image: "wseImageConfig", tts: "wseTtsConfig" };
export const worldSectionLabel = (t: T, key: string) => t(sectionKeys[key] ?? "wseUnknownSection").replace("{name}", humanise(key));
export const worldConfigLabel = (t: T, key: string) => t(configKeys[key] ?? "wseUnknownConfig").replace("{name}", humanise(key));
const fieldLabel = (t: T, key: string) => fieldKeys[key] ? t(fieldKeys[key]) : humanise(key);
const newId = () => globalThis.crypto?.randomUUID?.() ?? `world-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const clone = <TValue,>(value: TValue): TValue => structuredClone(value);
type RegistryOption = { id: string; label: string; type: string };
type Registry = Record<string, RegistryOption[]> & { allPhysical: RegistryOption[] };
const REFERENCE_TARGETS: Record<string, string> = {
  parent_location_id: "locations", location_id: "locations", landmark_id: "landmarks", item_id: "items",
  unlocking_item_ids: "items", held_stack_ids: "item_stacks", held_equipment_ids: "equipment",
  held_container_ids: "containers", turn_ids: "turns", event_id: "events", created_by_event_id: "events",
  contributed_by_event_ids: "events", character_id: "characters", observer_character_id: "characters",
  perspective_character_id: "characters", evidence_memory_ids: "memories", supporting_memory_ids: "memories",
  contradicting_memory_ids: "memories",
};
const ENUMS: Record<string, readonly string[]> = {
  "world.language": ["en", "zh"], "containers.state": ["hidden", "locked", "unlocked", "open"],
  "turns.type": ["user_input", "system_response", "system_continue"],
  "memories.support_type": ["direct", "inferred", "reported", "contradicts"],
  "intents.type": ["need", "obligation", "quest", "agenda", "aspiration", "relationship", "habit", "reaction"],
  "intents.status": ["active", "paused", "completed", "failed", "abandoned"],
  "intents.horizon": ["immediate", "short", "day", "long", "open_ended"],
  "entity_relationships.scope_type": ["world", "simulation"],
  "entity_relationships.visibility": ["public", "private", "objective"],
  "entity_relationships.kind": ["interpersonal", "spatial", "interaction", "goal", "compatibility", "generic"],
  "subjective_entity_claims.category": ["appearance", "personality", "preference", "aversion", "capability", "habit", "value", "relationship_expectation", "identity", "state", "safety", "access", "contents", "purpose", "condition", "ownership", "risk", "history", "other"],
  "subjective_entity_claims.stance": ["believes", "suspects", "uncertain", "doubts", "denies"],
  "entity_variable_sets.owner_type": ["world", "character", "background_character", "item", "item_stack", "equipment", "container", "location", "landmark", "body", "unknown"],
  "entity_variable_sets.value_type": ["string", "integer", "float", "boolean"],
};
const entityRefFields = new Set(["source", "target", "subject"]);
const enumValues = (path: string, key: string) => {
  const root = path.startsWith("sections.") ? path.split(".")[1] : path.split(".")[0];
  return ENUMS[`${root}.${key}`];
};

function ScalarFields({ value, path, onChange, onContext, t, registry }: { value: Record<string, JsonValue>; path: string; onChange: (value: Record<string, JsonValue>) => void; onContext: (value: EditorContext) => void; t: T; registry: Registry }) {
  return <div className="world-fields">{Object.entries(value).map(([key, field]) => {
    const fieldPath = `${path}.${key}`, label = fieldLabel(t, key);
    if (key === "id" || key === "creation_time" || key === "version" && path === "world") return <label key={key}>{label}<input value={String(field ?? "")} readOnly aria-readonly="true" /></label>;
    if (typeof field === "boolean") return <label className="world-check" key={key}><input type="checkbox" checked={field} onChange={(event) => onChange({ ...value, [key]: event.target.checked })} />{label}</label>;
    if (typeof field === "number") return <label key={key}>{label}<input type="number" value={field} onFocus={() => onContext({ path: fieldPath, selectedText: null, cursor: null })} onChange={(event) => onChange({ ...value, [key]: Number(event.target.value) })} /></label>;
    const choices = enumValues(path, key);
    if (choices && (typeof field === "string" || field === null)) return <label key={key}>{label}<select value={field ?? ""} onChange={(event) => onChange({ ...value, [key]: event.target.value || null })}><option value="">—</option>{choices.map((choice) => <option key={choice} value={choice}>{humanise(choice)}</option>)}</select></label>;
    const referenceTarget = REFERENCE_TARGETS[key];
    const referenceOptions = referenceTarget ? registry[referenceTarget] : (key === "owner_id" || key === "holder_id" || key === "owner_id") ? registry.allPhysical : null;
    if (referenceOptions && (typeof field === "string" || field === null)) return <label key={key}>{label}<select value={field ?? ""} onChange={(event) => onChange({ ...value, [key]: event.target.value || null })}><option value="">—</option>{referenceOptions.map((option) => <option key={`${option.type}:${option.id}`} value={option.id}>{option.label}</option>)}</select></label>;
    if (referenceOptions && Array.isArray(field) && field.every((item) => typeof item === "string")) return <label key={key}>{label}<select multiple value={field} onChange={(event) => onChange({ ...value, [key]: [...event.target.selectedOptions].map((option) => option.value) })}>{referenceOptions.map((option) => <option key={`${option.type}:${option.id}`} value={option.id}>{option.label}</option>)}</select></label>;
    if (entityRefFields.has(key) && field && typeof field === "object" && !Array.isArray(field)) { const ref = field as Record<string, JsonValue>; return <label key={key}>{label}<select value={String(ref.id ?? "")} onChange={(event) => { const option = registry.allPhysical.find((candidate) => candidate.id === event.target.value); onChange({ ...value, [key]: option ? { ...ref, id: option.id, name: option.label, type: option.type } : { ...ref, id: "", name: null } }); }}><option value="">—</option>{registry.allPhysical.map((option) => <option key={`${option.type}:${option.id}`} value={option.id}>{option.label}</option>)}</select></label>; }
    if (typeof field === "string" || field === null) { const long = typeof field === "string" && (field.length > 100 || /description|content|prompt|notes|plan|conditions|constraints/.test(key)); return <label key={key}>{label}{long ? <textarea rows={5} value={field ?? ""} onFocus={() => onContext({ path: fieldPath, selectedText: field || null, cursor: null })} onChange={(event) => onChange({ ...value, [key]: event.target.value })} /> : <input value={field ?? ""} onFocus={() => onContext({ path: fieldPath, selectedText: field || null, cursor: null })} onChange={(event) => onChange({ ...value, [key]: event.target.value })} />}</label>; }
    if (Array.isArray(field) && field.every((item) => typeof item === "string")) return <label key={key}>{label}<textarea rows={3} value={field.join("\n")} onFocus={() => onContext({ path: fieldPath, selectedText: null, cursor: null })} onChange={(event) => onChange({ ...value, [key]: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean) })} /><small>{t("wseOnePerLine")}</small></label>;
    if (Array.isArray(field) && field.every((item) => item && typeof item === "object" && !Array.isArray(item))) return <fieldset key={key}><legend>{label}</legend>{field.map((item, index) => <fieldset key={index}><legend>{index + 1}</legend><ScalarFields value={item as Record<string, JsonValue>} path={`${fieldPath}.${index}`} onContext={onContext} t={t} registry={registry} onChange={(nested) => onChange({ ...value, [key]: field.map((current, currentIndex) => currentIndex === index ? nested : current) })} /></fieldset>)}</fieldset>;
    if (field && typeof field === "object" && !Array.isArray(field)) return <fieldset key={key}><legend>{label}</legend><ScalarFields value={field as Record<string, JsonValue>} path={fieldPath} onContext={onContext} t={t} registry={registry} onChange={(nested) => onChange({ ...value, [key]: nested })} /></fieldset>;
    return <div className="world-unsupported" key={key}><strong>{label}</strong><span>{t("wsePreservedField")}</span></div>;
  })}</div>;
}

function CollectionEditor({ label, singular, rows, path, onChange, onContext, t, registry }: { label: string; singular: string; rows: Array<Record<string, JsonValue>>; path: string; onChange: (rows: Array<Record<string, JsonValue>>) => void; onContext: (value: EditorContext) => void; t: T; registry: Registry }) {
  const [selected, setSelected] = useState(0); const row = rows[selected];
  const add = () => { const next = [...rows, { id: newId(), name: `${t("wseNewItemPrefix")}${singular}` }]; onChange(next); setSelected(next.length - 1); };
  return <div className="world-collection"><aside><button className="primary" onClick={add}>{t("wseAddItem").replace("{item}", singular)}</button>{rows.map((item, index) => <button className={index === selected ? "active" : ""} key={String(item.id ?? index)} onClick={() => setSelected(index)}><strong>{String(item.name ?? item.title ?? item.id ?? `${label} ${index + 1}`)}</strong><small>{String(item.id ?? "")}</small></button>)}</aside><section>{row ? <><header><h2>{String(row.name ?? row.title ?? `${singular} ${selected + 1}`)}</h2><div><button className="secondary" onClick={() => { const next = [...rows]; next.splice(selected + 1, 0, { ...clone(row), id: newId() }); onChange(next); setSelected(selected + 1); }}>{t("duplicate")}</button><button className="danger-button" onClick={() => { onChange(rows.filter((_, index) => index !== selected)); setSelected(Math.max(0, selected - 1)); }}>{t("remove")}</button></div></header><ScalarFields value={row} path={`${path}.${String(row.id ?? selected)}`} onContext={onContext} t={t} registry={registry} onChange={(next) => onChange(rows.map((item, index) => index === selected ? next : item))} /></> : <div className="world-empty">{t("wseNoItems").replace("{items}", label)}</div>}</section></div>;
}

export function reviewWorld(data: WorldBundleData, t?: T) {
  const fallback: Partial<Record<MessageKey, string>> = { wseRequired: "{field} is required.", wseOnlyV1: "Only wse_world v1.0 is supported.", wseLanguageInvalid: "Language must be en or zh.", wseStartingTimeInvalid: "Starting time is not a valid date and time.", wseRowMissingId: "{section} row {number} has no ID.", wseDuplicateId: "Duplicate graph ID: {id}", wseEmptyDescription: "{section} row {number} has an empty description." };
  const tr = t ?? ((key: MessageKey) => fallback[key] ?? key), sectionName = (key: string) => t ? worldSectionLabel(t, key) : humanise(key), label = (key: string) => t ? fieldLabel(t, key) : humanise(key);
  const findings: Array<{ severity: "error" | "warning"; path: string; message: string }> = [];
  for (const key of ["id", "name", "starting_time", "language"]) if (!data.world[key]) findings.push({ severity: "error", path: `world.${key}`, message: tr("wseRequired").replace("{field}", label(key)) });
  if (data.spec !== "wse_world" || data.specVersion !== "1.0") findings.push({ severity: "error", path: "spec", message: tr("wseOnlyV1") });
  if (data.world.language !== "en" && data.world.language !== "zh") findings.push({ severity: "error", path: "world.language", message: tr("wseLanguageInvalid") });
  if (typeof data.world.starting_time === "string" && Number.isNaN(Date.parse(data.world.starting_time))) findings.push({ severity: "error", path: "world.starting_time", message: tr("wseStartingTimeInvalid") });
  const ids = new Set<string>();
  for (const section of WORLD_SECTIONS) for (const [index, row] of (data.sections[section] ?? []).entries()) { const id = typeof row.id === "string" ? row.id : "", replacements = (text: string) => text.replace("{section}", sectionName(section)).replace("{number}", String(index + 1)).replace("{id}", id); if (!id) findings.push({ severity: "error", path: `sections.${section}.${index}.id`, message: replacements(tr("wseRowMissingId")) }); else if (ids.has(id) || id === data.world.id) findings.push({ severity: "error", path: `sections.${section}.${id}.id`, message: replacements(tr("wseDuplicateId")) }); else ids.add(id); if ("description" in row && !String(row.description ?? "").trim()) findings.push({ severity: "warning", path: `sections.${section}.${id}.description`, message: replacements(tr("wseEmptyDescription")) }); }
  const targets = Object.fromEntries(WORLD_SECTIONS.map((section) => [section, new Set((data.sections[section] ?? []).map((row) => row.id).filter((id): id is string => typeof id === "string"))]));
  const physicalIds = new Set([String(data.world.id), ...["locations", "landmarks", "characters", "background_characters", "items", "item_stacks", "equipment", "containers"].flatMap((section) => [...targets[section]])]);
  for (const section of WORLD_SECTIONS) for (const row of data.sections[section] ?? []) for (const [key, value] of Object.entries(row)) {
    const expected = REFERENCE_TARGETS[key]; const accepted = expected ? targets[expected] : (key === "owner_id" || key === "holder_id") ? physicalIds : null;
    if (accepted) for (const reference of Array.isArray(value) ? value : [value]) if (typeof reference === "string" && reference && !accepted.has(reference)) findings.push({ severity: "error", path: `sections.${section}.${String(row.id)}.${key}`, message: `Unknown ${humanise(key)} reference: ${reference}` });
    if (entityRefFields.has(key) && value && typeof value === "object" && !Array.isArray(value)) { const reference = value as Record<string, JsonValue>; if (typeof reference.id === "string" && reference.id && !physicalIds.has(reference.id)) findings.push({ severity: "error", path: `sections.${section}.${String(row.id)}.${key}`, message: `Unknown ${humanise(key)} reference: ${reference.id}` }); }
  }
  for (const section of ["item_stacks", "equipment", "containers"]) for (const row of data.sections[section] ?? []) if (row.location_id && row.holder_id) findings.push({ severity: "error", path: `sections.${section}.${String(row.id)}.location_id`, message: `${humanise(section)} cannot have both a location and a holder.` });
  for (const row of data.sections.entity_relationships ?? []) { const source = row.source as Record<string, JsonValue> | undefined, target = row.target as Record<string, JsonValue> | undefined; if (source?.id && source.id === target?.id) findings.push({ severity: "error", path: `sections.entity_relationships.${String(row.id)}.target`, message: "Relationship source and target must be different." }); if ((row.visibility === "private" || row.private_description) && !row.perspective_character_id) findings.push({ severity: "error", path: `sections.entity_relationships.${String(row.id)}.perspective_character_id`, message: "Private relationships require a perspective character." }); }
  return findings;
}

export function worldCompleteness(data: WorldBundleData) {
  const values = [data.spec, data.specVersion, data.world.id, data.world.name, data.world.starting_time, data.world.language];
  const filled = values.filter((value) => typeof value === "string" ? Boolean(value.trim()) : value != null).length;
  return { filled, total: values.length, percent: Math.round(filled / values.length * 100) };
}

export function WorldBundlePage({ selected, page, dirty, status, onChange, onSave, onContext, onNavigate, onChangeResource, onDraft, t }: { selected: SelectedWorld; page: WorldPageKey; dirty: boolean; status: string; onChange: (value: WorldBundleData) => void; onSave: () => void; onContext: (value: EditorContext) => void; onNavigate: (page: WorldPageKey) => void; onChangeResource: () => void; onDraft: () => void; t: T }) {
  const data = selected.draft?.data; const findings = useMemo(() => data ? reviewWorld(data, t) : [], [data, t]);
  if (!data) return <section className="world-page"><header className="world-page-heading"><div><h1>{t("wseBundle")}</h1><p>{t("wseNoDraft")}</p></div><button className="secondary" onClick={onChangeResource}>{t("changeResource")}</button></header></section>;
  const registry = Object.fromEntries(WORLD_SECTIONS.map((section) => [section, (data.sections[section] ?? []).map((row, index) => ({ id: String(row.id ?? ""), label: String(row.name ?? row.title ?? row.summary ?? `${worldSectionLabel(t, section)} ${index + 1}`), type: section === "background_characters" ? "background_character" : section.replace(/s$/, "") }))])) as Registry;
  registry.allPhysical = [{ id: String(data.world.id), label: String(data.world.name), type: "world" }, ...["locations", "landmarks", "characters", "background_characters", "items", "item_stacks", "equipment", "containers"].flatMap((section) => registry[section] ?? [])];
  const shell = (heading: string, intro: string, body: React.ReactNode, overview = false) => <section className="world-page"><header className="world-page-heading"><div><p>{selected.resource.metadata.name}</p><h1>{heading}</h1><span>{intro}</span></div><div>{overview && <button className="secondary" onClick={onChangeResource}>{t("changeResource")}</button>}<button className="secondary" onClick={onDraft}>{t("wseCoauthor")}</button><button className="primary" disabled={!dirty || status === "saving"} onClick={onSave}>{status === "saving" ? t("saving") : t("wseSave")}</button></div></header>{body}</section>;
  if (page === "world-overview") { const completeness = worldCompleteness(data); return shell(t("wseOverviewTitle"), t("wseOverviewIntro"), <><div className="metric-grid"><article><span>{t("completion")}</span><strong>{completeness.percent}%</strong><small>{completeness.filled} / {completeness.total} {t("fieldsFilled")}</small></article><article><span>{t("wseGraphRecords")}</span><strong>{Object.values(data.sections).reduce((sum, rows) => sum + rows.length, 0)}</strong></article><article><span>{t("wseCharacters")}</span><strong>{(data.sections.characters?.length ?? 0) + (data.sections.background_characters?.length ?? 0)}</strong></article><article><span>{t("wsePrompts")}</span><strong>{data.prompts.length}</strong></article><article><span>{t("wseFindings")}</span><strong>{findings.length}</strong></article></div><p className="estimate-note">{t("wseCompletenessNote")}</p><section className="world-review"><h2>{t("wseDeterministicReview")}</h2>{findings.length ? findings.map((finding) => <button key={`${finding.path}-${finding.message}`} onClick={() => { onContext({ path: finding.path, selectedText: null, cursor: null }); const match = finding.path.match(/^sections\.([^.]+)/); onNavigate(match ? `world-section:${match[1]}` as WorldPageKey : "world-details"); }}><b className={finding.severity}>{finding.severity === "error" ? "!" : "△"}</b><span>{finding.message}<small>{finding.path}</small></span></button>) : <p>{t("wseNoProblems")}</p>}</section><section className="world-summary"><h2>{t("wseBundleContents")}</h2>{WORLD_SECTIONS.map((section) => <button key={section} onClick={() => onNavigate(`world-section:${section}`)}><span>{worldSectionLabel(t, section)}</span><strong>{data.sections[section]?.length ?? 0}</strong></button>)}</section></>, true); }
  if (page === "world-details") return shell(t("wseWorldAuthor"), t("wseWorldAuthorIntro"), <><section className="world-panel"><h2>{t("wseWorld")}</h2><ScalarFields value={data.world} path="world" onContext={onContext} t={t} registry={registry} onChange={(world) => onChange({ ...data, world })} /></section><section className="world-panel"><header><h2>{t("wseAuthor")}</h2>{!data.author && <button onClick={() => onChange({ ...data, author: { id: newId(), name: "", url: "" } })}>{t("wseAddAuthor")}</button>}</header>{data.author && <ScalarFields value={data.author} path="author" onContext={onContext} t={t} registry={registry} onChange={(author) => onChange({ ...data, author })} />}</section></>);
  const section = page.startsWith("world-section:") ? page.slice(14) : null;
  if (section) { const label = worldSectionLabel(t, section), singular = t(singularKeys[section] ?? "wseItem"); return shell(label, t("wseCollectionIntro").replace("{collection}", label), <CollectionEditor label={label} singular={singular} rows={data.sections[section] ?? []} path={`sections.${section}`} onContext={onContext} t={t} registry={registry} onChange={(rows) => onChange({ ...data, sections: { ...data.sections, [section]: rows } })} />); }
  const config = page.startsWith("world-config:") ? page.slice(13) : null;
  if (config) { const label = worldConfigLabel(t, config); return shell(label, t("wseConfigIntro"), <CollectionEditor label={label} singular={t("wseConfigAssignment")} rows={data.configs[config] ?? []} path={`configs.${config}`} onContext={onContext} t={t} registry={registry} onChange={(rows) => onChange({ ...data, configs: { ...data.configs, [config]: rows } })} />); }
  if (page === "world-prompts") return shell(t("wsePrompts"), t("wsePromptsIntro"), <CollectionEditor label={t("wsePrompts")} singular={t("wsePrompt")} rows={data.prompts} path="prompts" onContext={onContext} t={t} registry={registry} onChange={(prompts) => onChange({ ...data, prompts })} />);
  if (page === "world-workflows") return shell(t("wseWorkflows"), t("wseWorkflowsIntro"), <CollectionEditor label={t("wseWorkflows")} singular={t("wseWorkflow")} rows={data.workflows} path="workflows" onContext={onContext} t={t} registry={registry} onChange={(workflows) => onChange({ ...data, workflows })} />);
  return shell(t("wseMedia"), t("wseMediaIntro"), <CollectionEditor label={t("wseMedia")} singular={t("wseMediaItem")} rows={data.media.map((item) => ({ ...item.record, id: item.mediaId, imageResourceId: item.imageResourceId }))} path="media" onContext={onContext} t={t} registry={registry} onChange={(rows) => onChange({ ...data, media: rows.map((row) => ({ mediaId: String(row.id), imageResourceId: typeof row.imageResourceId === "string" ? row.imageResourceId : null, record: Object.fromEntries(Object.entries(row).filter(([key]) => key !== "imageResourceId")) })) })} />);
}
